export const LANGUAGES = [
  { value: "afrikaans", label: "Afrikaans" },
  { value: "albanian", label: "Albanian (Shqip)" },
  { value: "amharic", label: "Amharic (አማርኛ)" },
  { value: "arabic", label: "Arabic (العربية)" },
  { value: "armenian", label: "Armenian (Հայերեն)" },
  { value: "azerbaijani", label: "Azerbaijani (Azərbaycan)" },
  { value: "basque", label: "Basque (Euskara)" },
  { value: "belarusian", label: "Belarusian (Беларуская)" },
  { value: "bengali", label: "Bengali (বাংলা)" },
  { value: "bosnian", label: "Bosnian (Bosanski)" },
  { value: "bulgarian", label: "Bulgarian (Български)" },
  { value: "burmese", label: "Burmese (မြန်မာဘာသာ)" },
  { value: "catalan", label: "Catalan (Català)" },
  { value: "mandarin", label: "Chinese, Mandarin (普通话)" },
  { value: "croatian", label: "Croatian (Hrvatski)" },
  { value: "czech", label: "Czech (Čeština)" },
  { value: "danish", label: "Danish (Dansk)" },
  { value: "dutch", label: "Dutch (Nederlands)" },
  { value: "english", label: "English" },
  { value: "estonian", label: "Estonian (Eesti)" },
  { value: "finnish", label: "Finnish (Suomi)" },
  { value: "french", label: "French (Français)" },
  { value: "georgian", label: "Georgian (ქართული)" },
  { value: "german", label: "German (Deutsch)" },
  { value: "greek", label: "Greek (Ελληνικά)" },
  { value: "gujarati", label: "Gujarati (ગુજરાતી)" },
  { value: "hausa", label: "Hausa" },
  { value: "hebrew", label: "Hebrew (עברית)" },
  { value: "hindi", label: "Hindi (हिन्दी)" },
  { value: "hungarian", label: "Hungarian (Magyar)" },
  { value: "icelandic", label: "Icelandic (Íslenska)" },
  { value: "indonesian", label: "Indonesian (Bahasa Indonesia)" },
  { value: "italian", label: "Italian (Italiano)" },
  { value: "japanese", label: "Japanese (日本語)" },
  { value: "kannada", label: "Kannada (ಕನ್ನಡ)" },
  { value: "kazakh", label: "Kazakh (Қазақша)" },
  { value: "khmer", label: "Khmer (ភាសាខ្មែរ)" },
  { value: "korean", label: "Korean (한국어)" },
  { value: "lao", label: "Lao (ລາວ)" },
  { value: "latvian", label: "Latvian (Latviešu)" },
  { value: "lithuanian", label: "Lithuanian (Lietuvių)" },
  { value: "macedonian", label: "Macedonian (Македонски)" },
  { value: "malay", label: "Malay (Bahasa Melayu)" },
  { value: "malayalam", label: "Malayalam (മലയാളം)" },
  { value: "marathi", label: "Marathi (मराठी)" },
  { value: "mongolian", label: "Mongolian (Монгол)" },
  { value: "nepali", label: "Nepali (नेपाली)" },
  { value: "norwegian", label: "Norwegian (Norsk)" },
  { value: "pashto", label: "Pashto (پښتو)" },
  { value: "persian", label: "Persian/Farsi (فارسی)" },
  { value: "polish", label: "Polish (Polski)" },
  { value: "portuguese", label: "Portuguese (Português)" },
  { value: "romanian", label: "Romanian (Română)" },
  { value: "russian", label: "Russian (Русский)" },
  { value: "serbian", label: "Serbian (Српски)" },
  { value: "sinhala", label: "Sinhala (සිංහල)" },
  { value: "slovak", label: "Slovak (Slovenčina)" },
  { value: "slovenian", label: "Slovenian (Slovenščina)" },
  { value: "spanish", label: "Spanish (Español)" },
  { value: "swahili", label: "Swahili (Kiswahili)" },
  { value: "swedish", label: "Swedish (Svenska)" },
  { value: "tagalog", label: "Tagalog/Filipino" },
  { value: "tamil", label: "Tamil (தமிழ்)" },
  { value: "telugu", label: "Telugu (తెలుగు)" },
  { value: "thai", label: "Thai (ไทย)" },
  { value: "turkish", label: "Turkish (Türkçe)" },
  { value: "ukrainian", label: "Ukrainian (Українська)" },
  { value: "urdu", label: "Urdu (اردو)" },
  { value: "uzbek", label: "Uzbek (Oʻzbekcha)" },
  { value: "vietnamese", label: "Vietnamese (Tiếng Việt)" },
  { value: "yoruba", label: "Yoruba" },
  { value: "zulu", label: "Zulu (isiZulu)" },
  { value: "other", label: "Other" },
] as const;

export type LanguageValue = typeof LANGUAGES[number]["value"];